#pragma once
//#include "queue.h"
//#include "action.h"
//#include "entity.h"
//#include "BattleState.h"
#include "DungeonState.h"
//#include "StateMachine.h"
//#include "SDLfoundation.h"
#include "TextboxState.h"
//#include <iostream>
//#include <SDL.h>
//#include <SDL_image.h>
//#include <SDL_ttf.h>
//#include <vector>
//#include <Windows.h>